### ISSUE TITLE
Error running notebook from shell on mac

### ISSUE THREAD

**Issue by bnlawrence** [ES-DOC/esdoc-nb-shell#1]
(This is likely an issue to do with how I've installed pygraphviz and pygtk into which python etc on mac, recorded here so we address it in the readme once I've worked out how to fix it).

```
#!python
 esdoc-notebook-open
2015-07-26 07:55:33.660 Python[35188:1107] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
Traceback (most recent call last):
  File "/Users/BNL28/code/esdoc-nb-shell/local/source/esdoc-nb/simpleRun.py", line 3, in <module>
    from esdoc_nb import pseudo_cimNB
  File "/Users/BNL28/Code/esdoc-nb-shell/local/source/esdoc-nb/esdoc_nb/__init__.py", line 1, in <module>
    from pseudo_cimNB import __version__
  File "/Users/BNL28/Code/esdoc-nb-shell/local/source/esdoc-nb/esdoc_nb/pseudo_cimNB.py", line 8, in <module>
    import pseudo_view as vw
  File "/Users/BNL28/Code/esdoc-nb-shell/local/source/esdoc-nb/esdoc_nb/pseudo_view.py", line 11, in <module>
    import pseudo_help as ph
  File "/Users/BNL28/Code/esdoc-nb-shell/local/source/esdoc-nb/esdoc_nb/pseudo_help.py", line 6, in <module>
    import umlview as uml
  File "/Users/BNL28/Code/esdoc-nb-shell/local/source/esdoc-nb/esdoc_nb/umlview.py", line 7, in <module>
    import pygraphviz as pgv
ImportError: No module named pygraphviz
```

**Comment by bnlawrence** [comment]
My "science" mac python is  /opt/local/bin/python2.7, but it is not the default python on my mac shell.

**Comment by bnlawrence** [comment]
Ok, I can make this work by manually putting python2.7 into the python command at the bottom of open.sh. There is probably a cleaner way to do this ...

**Comment by momipsl** [comment]
Do not edit open.sh manually there is no need and it will interfere with updating the shell.  There are several wasy to acheive want you wish from the command line:
<pre><code>export PATH=/usr/local/Cellar/python/2.7.10_2/bin:$PATH</pre></code>
Alternatively
<pre><code>alias python=/opt/local/bin/python2.7</pre></code>

I simply place the PATH assignment statement into my .bash_profile file.

**Comment by bnlawrence** [comment]
On linux it is dangerous to redefine your default python, since utilities can run with your default python and behave differently. Also, if one is dealing with multiple projects using different version of python, this is not a solution. We need a solution which doesn't require changing the default python in my bash script.

**Comment by bnlawrence** [comment]
I started trying to hack the aliases script to do this using an optional argument to redefine the python, but things are complicated in that not only do I want to change the default path, I want to ensure I use a specific version of python. My bash skills aren't up to the string handling required ... quickly ... For now, I can live with hacking my version of the script as noted above, but I appreciate that's brittle. We should find a better solution.

**Comment by momipsl** [comment]
I am adding a change to allow the user to specify an environment variable: ESDOC-NOTEBOOK-PYTHON that will point to the python executable to be used to run the notebook.  The user will need to add this to their .bash_profile file and they will be good to go.
